#-------------------------------
# General Site Settings
baseURL = "https://hot-deal.store"

# Multilingual Setting
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  en = { weight = 1 }
  zh-cn = { weight = 2 }
  zh-tw = { weight = 3 }
  ja = { weight = 4 }
  ko = { weight = 5 }
  vi = { weight = 6 }
  th = { weight = 7 }
  id = { weight = 8 }
  hi = { weight = 9 }
  es = { weight = 10 }
  pt = { weight = 11 }
  fr = { weight = 12 }
  it = { weight = 13 }
  de = { weight = 14 }
  tr = { weight = 15 }

[params]
  logo = "/images/logo.png"
  logo_dark = "/images/logo.png"
  color_scheme = "auto"

[permalinks]
  post = "/:sections/:slug/"

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  author = "authors"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false

#-------------------------------
# Tags Section Settings
[params.tags_section]
  enable = true
  number_posts = 3
  number_columns = 3

[[params.tag]]
  tag = "lifestyle"
[[params.tag]]
  tag = "shopping"
[[params.tag]]
  tag = "business"
[[params.tag]]
  tag = "food"
[[params.tag]]
  tag = "sport"

#-------------------------------
# Authors Section Settings
[params.authors_section]
  enable = true

#-------------------------------
# Footer Settings
[params.footer]

# Social Links
[[params.social]]
  icon = "fa-brands fa-x-twitter"
  name = "Twitter"
  link = "https://twitter.com"
[[params.social]]
  icon = "fa-brands fa-facebook"
  name = "Facebook"
  link = "https://facebook.com"
[[params.social]]
  icon = "fa-brands fa-codepen"
  name = "Codepen"
  link = "https://codepen.io/"
[[params.social]]
  icon = "fa-brands fa-pinterest"
  name = "Pinterest"
  link = "https://pinterest.com"
[[params.social]]
  icon = "fa-brands fa-github"
  name = "Github"
  link = "https://github.com"
[[params.social]]
  icon = "fa-brands fa-youtube"
  name = "Youtube"
  link = "https://youtube.com"

# Newsletter
[params.mailchimp]
  enable = true
  mailchimp__identifier = "gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp"

#-------------------------------
# Contact Settings
[params.contact]
  email = "your@email.com"

#-------------------------------
# Comment Section (Disqus)
[params.disqus]
  enable = true
  disqusShortname = "anvod-studio-test"