# config/_default/config.toml
baseURL = "https://hot-deal.store/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.ko]
    contentDir = "content/ko"
    languageName = "한국어"
    weight = 2
  [languages.ja]
    contentDir = "content/ja"
    languageName = "日本語"
    weight = 3

[params]
  logo = "/images/logo.png"
  logo_dark = "/images/logo.png"
  color_scheme = "auto"

  [params.hero]
    enable = true
    hero__title = "One Stop Daily News, Article, Inspiration, and Tips."
    hero__description = "Features productivity, tips, inspiration and strategies for massive profits. Find out how to set up a successful blog or how to make yours even better!"

  [params.tags_section]
    enable = true
    number_posts = 3
    number_columns = 3

  [[params.tag]]
    tag = "lifestyle"
  [[params.tag]]
    tag = "shopping"
  [[params.tag]]
    tag = "business"
  [[params.tag]]
    tag = "food"
  [[params.tag]]
    tag = "sport"

  [params.authors_section]
    enable = true
    section_title = "Meet our authors"

  [params.footer]
    footer__description = "Features productivity, tips, inspiration and strategies for massive profits. Find out how to set up a successful blog or how to make yours even better!"

  [[params.social]]
    icon = "fa-brands fa-x-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "fa-brands fa-facebook"
    name = "Facebook"
    link = "https://facebook.com"

  [[params.social]]
    icon = "fa-brands fa-codepen"
    name = "Codepen"
    link = "https://codepen.io/"

  [[params.social]]
    icon = "fa-brands fa-pinterest"
    name = "Pinterest"
    link = "https://pinterest.com"

  [[params.social]]
    icon = "fa-brands fa-github"
    name = "Github"
    link = "https://github.com"

  [[params.social]]
    icon = "fa-brands fa-youtube"
    name = "Youtube"
    link = "https://youtube.com"

  [params.mailchimp]
    enable = true
    mailchimp__title = "Get interesting news"
    mailchimp__description = "Subscribe to our newsletter and we'll send you the emails of latest posts."
    mailchimp__identifier = "gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp"
    mailchimp__input__text = "Your email address"
    mailchimp__button__text = "Subscribe"

  [params.contact]
    email = "your@email.com"

  [params.disqus]
    enable = true
    disqusShortname = "anvod-studio-test"

[taxonomies]
  author = "authors"
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false

[permalinks]
  posts = "/:sections/:slug/"