#-------------------------------
# General Site Settings
baseURL = "https://hugo-test92.netlify.app"
languageCode = "en-US"
defaultContentLanguage = "en-US"
defaultContentLanguageInSubdir = true
contentDir = "content/en-US"
title = "Danto"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.

[pagination]
pagerSize = 12

[sitemap]
  changefreq = "monthly"
  priority = 0.5

[languages]
  [languages.en-US]
    languageName = "English (US)"
    weight = 1

  [languages.en-CA]
    languageName = "English (Canada)"
    weight = 2

  [languages.en-GB]
    languageName = "English (UK)"
    weight = 3

  [languages.en-AU]
    languageName = "English (Australia)"
    weight = 4

  [languages.en-IN]
    languageName = "English (India)"
    weight = 5

  [languages.en-SG]
    languageName = "English (Singapore)"
    weight = 6

  [languages.es-ES]
    languageName = "Español (España)"
    weight = 7

  [languages.es-MX]
    languageName = "Español (México)"
    weight = 8

  [languages.es-CO]
    languageName = "Español (Colombia)"
    weight = 9

  [languages.es-AR]
    languageName = "Español (Argentina)"
    weight = 10

  [languages.es-PE]
    languageName = "Español (Perú)"
    weight = 11

  [languages.pt-PT]
    languageName = "Português (Portugal)"
    weight = 12

  [languages.pt-BR]
    languageName = "Português (Brasil)"
    weight = 13

  [languages.fr]
    languageName = "Français"
    weight = 14

  [languages.it]
    languageName = "Italiano"
    weight = 15

  [languages.de]
    languageName = "Deutsch"
    weight = 16

  [languages.zh-CN]
    languageName = "中文 (中国)"
    weight = 17

  [languages.zh-TW]
    languageName = "中文 (台灣)"
    weight = 18

  [languages.ja]
    languageName = "日本語"
    weight = 19

  [languages.ko]
    languageName = "한국어"
    weight = 20

  [languages.id]
    languageName = "Bahasa Indonesia"
    weight = 21

  [languages.vi]
    languageName = "Tiếng Việt"
    weight = 22

  [languages.th]
    languageName = "ไทย"
    weight = 23

  [languages.tr]
    languageName = "Türkçe"
    weight = 24

  [languages.hi]
    languageName = "हिन्दी"
    weight = 25
    

#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Latest"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Authors"
    url = "/authors/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "Pages"
    weight = 5
    hasChildren = true

  [[menu.main]]
    parent = "Pages"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    parent = "Pages"
    name = "Elements"
    url = "/elements/"
    weight = 2

  [[menu.main]]
    parent = "Pages"
    name = "Contact"
    url = "/contact/"
    weight = 3

  [[menu.main]]
    parent = "Pages"
    name = "Videos"
    url = "/videos/"
    weight = 4

  [[menu.main]]
    parent = "Pages"
    name = "Featured"
    url = "/featured/"
    weight = 5

  # Call to action button
  [params.cta_button]
    enable = true
    cta_button_link = "/contact/"
    cta_button_text = "Get in touch"


[params]
  logo = "/images/logo.png" # You can add own logo. For example "/images/logo.png".
  logo_dark = "/images/logo.png"
  description = "Danto is a news and magazine Hugo theme"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero__title = "One Stop Daily News, Article, Inspiration, and Tips."
    hero__description = "Features productivity, tips, inspiration and strategies for massive profits. Find out how to set up a successful blog or how to make yours even better!"


#-------------------------------

# Categories Section Settings
[params.categories_section]
  enable = true
  number_posts = 3
  number_columns = 3

# Tags Section Settings
[params.tags_section]
  enable = true
  number_posts = 3 # To control how many posts to show under each tag section, set the value to a number. Three is the default.
  number_columns = 3 # You can specify the number of columns from 1-4 for large screen resolution. By default, the theme uses three columns grid.

[[params.category]]
  category = "mobile"
[[params.category]]
  category = "technology"
# Add more categories as needed

[[params.tag]]
  tag = "lifestyle"
[[params.tag]]
  tag = "shopping"
[[params.tag]]
  tag = "business"
[[params.tag]]
  tag = "food"
[[params.tag]]
  tag = "sport"
# You can add many tag sections to the homepage; each section will show the recent posts by the tag.


  #-------------------------------
  # Authors Section Settings
  [params.authors_section]
    enable = false
    section_title = "Meet our authors"


  #-------------------------------
  # Footer Settings
  [params.footer]
    footer__description = "Features productivity, tips, inspiration and strategies for massive profits. Find out how to set up a successful blog or how to make yours even better!"

  # Social Links
  [[params.social]]
    icon = "fa-brands fa-x-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "fa-brands fa-facebook"
    name = "Facebook"
    link = "https://facebook.com"

  [[params.social]]
    icon = "fa-brands fa-codepen"
    name = "Codepen"
    link = "https://codepen.io/"

  [[params.social]]
    icon = "fa-brands fa-pinterest"
    name = "Pinterest"
    link = "https://pinterest.com"

  [[params.social]]
    icon = "fa-brands fa-github"
    name = "Github"
    link = "https://github.com"

  [[params.social]]
    icon = "fa-brands fa-youtube"
    name = "Youtube"
    link = "https://youtube.com"

  # Example of adding a new link to the footer section:
  # [[params.social]]
  #   icon = "fa-brands fa-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://fontawesome.com/icons


  # Newsletter
  [params.mailchimp]
    enable = true
    mailchimp__title = "Get interesting news"
    mailchimp__description = "Subscribe to our newsletter and we’ll send you the emails of latest posts."
    mailchimp__identifier = "gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp" # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
    mailchimp__input__text = "Your email address"
    mailchimp__button__text = "Subscribe"


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "your@email.com" # Add your form_id

    # NOTE
    # Danto comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test



mainSections = ["posts", "docs", "news"]  # 여기서 'news'나'docs'등 새로 추가한 섹션이 포함되어야 함


[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"
  series = "series"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2


[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false

