main:
  - name: "Inicio"
    url: "/"
    weight: 1
  - name: "Últimos"
    url: "/posts/"
    weight: 2
  - name: "Autores"
    url: "/authors/"
    weight: 3
  - name: "Etiquetas"
    url: "/tags/"
    weight: 4
  - name: "Páginas"
    weight: 5
    hasChildren: true
  - name: "Acerca de"
    url: "/about/"
    parent: "Páginas"
    weight: 1
  - name: "Elementos"
    url: "/elements/"
    parent: "Páginas"
    weight: 2
  - name: "Contacto"
    url: "/contact/"
    parent: "Páginas"
    weight: 3
  - name: "Videos"
    url: "/videos/"
    parent: "Páginas"
    weight: 4
  - name: "Destacado"
    url: "/featured/"
    parent: "Páginas"
    weight: 5
