# config.toml

baseURL = "https://hot-deal.store/"
title = "Danto"
defaultContentLanguage = "us"
defaultContentLanguageInSubdir = false
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.

# 언어 설정
[languages]
  [languages.us]
    languageCode = "en-us"
    contentDir = "content/us"
    languageName = "English (US)"
    weight = 1
    title = "Danto"
    [languages.us.params]
      description = "Danto is a news and magazine Hugo theme"
      dateFormat = "January 2, 2006"
      shortDateFormat = "Jan 2"

  [languages.in]
    languageCode = "en-in"
    contentDir = "content/in"
    languageName = "English (India)"
    weight = 2
    title = "Danto"
    [languages.in.params]
      description = "Danto is a news and magazine Hugo theme"
      dateFormat = "2 January, 2006"
      shortDateFormat = "2 Jan"

  [languages.cn]
    languageCode = "zh-cn"
    contentDir = "content/cn"
    languageName = "简体中文"
    weight = 3
    title = "丹托"
    [languages.cn.params]
      description = "丹托是一个新闻和杂志Hugo主题"
      dateFormat = "2006年1月2日"
      shortDateFormat = "1月2日"

  [languages.tw]
    languageCode = "zh-tw"
    contentDir = "content/tw"
    languageName = "繁體中文"
    weight = 4
    title = "丹托"
    [languages.tw.params]
      description = "丹托是一個新聞和雜誌Hugo主題"
      dateFormat = "2006年1月2日"
      shortDateFormat = "1月2日"

  [languages.mx]
    languageCode = "es-mx"
    contentDir = "content/mx"
    languageName = "Español (México)"
    weight = 5
    title = "Danto"
    [languages.mx.params]
      description = "Danto es un tema Hugo para noticias y revistas"
      dateFormat = "2 de enero de 2006"
      shortDateFormat = "2 ene"

  [languages.ae]
    languageCode = "ar-ae"
    contentDir = "content/ae"
    languageName = "العربية"
    weight = 6
    title = "دانتو"
    [languages.ae.params]
      description = "دانتو هو موضوع Hugo للأخبار والمجلات"
      dateFormat = "2 يناير 2006"
      shortDateFormat = "2 يناير"

  [languages.br]
    languageCode = "pt-br"
    contentDir = "content/br"
    languageName = "Português (Brasil)"
    weight = 7
    title = "Danto"
    [languages.br.params]
      description = "Danto é um tema Hugo para notícias e revistas"
      dateFormat = "2 de janeiro de 2006"
      shortDateFormat = "2 jan"

  [languages.jp]
    languageCode = "ja-jp"
    contentDir = "content/jp"
    languageName = "日本語"
    weight = 8
    title = "ダント"
    [languages.jp.params]
      description = "ダントはニュースと雑誌のためのHugoテーマです"
      dateFormat = "2006年1月2日"
      shortDateFormat = "1月2日"

  [languages.de]
    languageCode = "de-de"
    contentDir = "content/de"
    languageName = "Deutsch"
    weight = 9
    title = "Danto"
    [languages.de.params]
      description = "Danto ist ein Hugo-Thema für Nachrichten und Magazine"
      dateFormat = "2. Januar 2006"
      shortDateFormat = "2. Jan"

  [languages.kr]
    languageCode = "ko-kr"
    contentDir = "content/kr"
    languageName = "한국어"
    weight = 10
    title = "단토"
    [languages.kr.params]
      description = "단토는 뉴스와 매거진을 위한 Hugo 테마입니다"
      dateFormat = "2006년 1월 2일"
      shortDateFormat = "1월 2일"

  [languages.fr]
    languageCode = "fr-fr"
    contentDir = "content/fr"
    languageName = "Français"
    weight = 11
    title = "Danto"
    [languages.fr.params]
      description = "Danto est un thème Hugo pour les actualités et les magazines"
      dateFormat = "2 janvier 2006"
      shortDateFormat = "2 janv"

  [languages.vn]
    languageCode = "vi-vn"
    contentDir = "content/vn"
    languageName = "Tiếng Việt"
    weight = 12
    title = "Danto"
    [languages.vn.params]
      description = "Danto là chủ đề Hugo cho tin tức và tạp chí"
      dateFormat = "2 tháng 1 năm 2006"
      shortDateFormat = "2 Th1"

  [languages.it]
    languageCode = "it-it"
    contentDir = "content/it"
    languageName = "Italiano"
    weight = 13
    title = "Danto"
    [languages.it.params]
      description = "Danto è un tema Hugo per notizie e riviste"
      dateFormat = "2 gennaio 2006"
      shortDateFormat = "2 gen"

  [languages.tr]
    languageCode = "tr-tr"
    contentDir = "content/tr"
    languageName = "Türkçe"
    weight = 14
    title = "Danto"
    [languages.tr.params]
      description = "Danto, haberler ve dergiler için bir Hugo temasıdır"
      dateFormat = "2 Ocak 2006"
      shortDateFormat = "2 Oca"

  [languages.id]
    languageCode = "id-id"
    contentDir = "content/id"
    languageName = "Bahasa Indonesia"
    weight = 15
    title = "Danto"
    [languages.id.params]
      description = "Danto adalah tema Hugo untuk berita dan majalah"
      dateFormat = "2 Januari 2006"
      shortDateFormat = "2 Jan"

  [languages.th]
    languageCode = "th-th"
    contentDir = "content/th"
    languageName = "ไทย"
    weight = 16
    title = "แดนโต"
    [languages.th.params]
      description = "แดนโตเป็นธีม Hugo สำหรับข่าวและนิตยสาร"
      dateFormat = "2 มกราคม 2006"
      shortDateFormat = "2 ม.ค."


# 메타 및 테마 관련 설정

[params]
  logo = "/images/logo.png"
  logo_dark = "/images/logo.png"
  color_scheme = "auto"
  mainSections = ["posts", "news", "docs"]


  [params.hero]
    enable = true

  [params.tags_section]
    enable = true
    number_posts = 3
    number_columns = 3

  [[params.tag]]
    tag = "lifestyle"
  [[params.tag]]
    tag = "shopping"
  [[params.tag]]
    tag = "business"
  [[params.tag]]
    tag = "food"
  [[params.tag]]
    tag = "sport"

  [params.authors_section]
    enable = false
    
  [params.footer]
    footer__description = "Features productivity, tips, inspiration and strategies for massive profits. Find out how to set up a successful blog or how to make yours even better!"

  [[params.social]]
    icon = "fa-brands fa-x-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "fa-brands fa-facebook"
    name = "Facebook"
    link = "https://facebook.com"

  [[params.social]]
    icon = "fa-brands fa-codepen"
    name = "Codepen"
    link = "https://codepen.io/"

  [[params.social]]
    icon = "fa-brands fa-pinterest"
    name = "Pinterest"
    link = "https://pinterest.com"

  [[params.social]]
    icon = "fa-brands fa-github"
    name = "Github"
    link = "https://github.com"

  [[params.social]]
    icon = "fa-brands fa-youtube"
    name = "Youtube"
    link = "https://youtube.com"

  [params.mailchimp]
    enable = true
    mailchimp__title = "Get interesting news"
    mailchimp__description = "Subscribe to our newsletter and we'll send you the emails of latest posts."
    mailchimp__identifier = "gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp"
    mailchimp__input__text = "Your email address"
    mailchimp__button__text = "Subscribe"

  [params.contact]
    email = "your@email.com"

  [params.disqus]
    enable = true
    disqusShortname = "anvod-studio-test"

  [params.cta_button]
    enable = true
    cta_button_link = "/contact/"
    cta_button_text = "Get in touch"

[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false

[permalinks]
  posts = "/:slug/"
  news = "/:sections/:slug/"
  docs = "/:sections/:slug/"