# config/ja/config.toml
title = "ダント"
languageCode = "ja-jp"

[params]
  description = "ダントはニュースと雑誌のためのHugoテーマです"

[[menu.main]]
  name = "ホーム"
  url = "/"
  weight = 1

[[menu.main]]
  name = "最新"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "著者"
  url = "/authors/"
  weight = 3

[[menu.main]]
  name = "タグ"
  url = "/tags/"
  weight = 4

[[menu.main]]
  name = "ページ"
  weight = 5
  hasChildren = true

[[menu.main]]
  parent = "ページ"
  name = "について"
  url = "/about/"
  weight = 1

[[menu.main]]
  parent = "ページ"
  name = "要素"
  url = "/elements/"
  weight = 2

[[menu.main]]
  parent = "ページ"
  name = "お問い合わせ"
  url = "/contact/"
  weight = 3

[[menu.main]]
  parent = "ページ"
  name = "動画"
  url = "/videos/"
  weight = 4

[[menu.main]]
  parent = "ページ"
  name = "おすすめ"
  url = "/featured/"
  weight = 5

[params.cta_button]
  enable = true
  cta_button_link = "/contact/"
  cta_button_text = "お問い合わせ"