# config/en/config.toml
title = "Danto"
languageCode = "en-us"

[params]
  description = "Danto is a news and magazine Hugo theme"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Latest"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Authors"
  url = "/authors/"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 4

[[menu.main]]
  name = "Pages"
  weight = 5
  hasChildren = true

[[menu.main]]
  parent = "Pages"
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  parent = "Pages"
  name = "Elements"
  url = "/elements/"
  weight = 2

[[menu.main]]
  parent = "Pages"
  name = "Contact"
  url = "/contact/"
  weight = 3

[[menu.main]]
  parent = "Pages"
  name = "Videos"
  url = "/videos/"
  weight = 4

[[menu.main]]
  parent = "Pages"
  name = "Featured"
  url = "/featured/"
  weight = 5

[params.cta_button]
  enable = true
  cta_button_link = "/contact/"
  cta_button_text = "Get in touch"