languageCode = "ja-jp"
languageName = "日本語"
title = "あなたのサイトタイトル"
weight = 4

[params]
  description = "Dantoはニュースと雑誌のためのHugoテーマです"

[menu]
  [[menu.main]]
    name = "ホーム"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "最新"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "著者"
    url = "/authors/"
    weight = 3
  [[menu.main]]
    name = "タグ"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    name = "ページ"
    weight = 5
    hasChildren = true
  [[menu.main]]
    parent = "ページ"
    name = "について"
    url = "/about/"
    weight = 1
  [[menu.main]]
    parent = "ページ"
    name = "連絡先"
    url = "/contact/"
    weight = 2

[params.cta_button]
  cta_button_text = "お問い合わせ"

[params.hero]
  hero__title = "デイリーニュース、記事、インスピレーション、ヒントのワンストップサイト。"
  hero__description = "生産性、ヒント、インスピレーション、そして大きな利益を得るための戦略を特集しています。成功するブログの立ち上げ方、または既存のブログをより良くする方法を見つけましょう！"

[params.authors_section]
  section_title = "私たちの著者たち"

[params.footer]
  footer__description = "生産性、ヒント、インスピレーション、そして大きな利益を得るための戦略を特集しています。成功するブログの立ち上げ方、または既存のブログをより良くする方法を見つけましょう！"

[params.mailchimp]
  mailchimp__title = "興味深いニュースを受け取る"
  mailchimp__description = "ニュースレターを購読すると、最新の投稿のメールをお送りします。"
  mailchimp__input__text = "メールアドレス"
  mailchimp__button__text = "購読する"